apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    basicAuth: true
    basicAuthUser: ""
    secureJsonData:
      basicAuthPassword: $INFLUXDB_API_TOKEN
    jsonData:
      version: InfluxQL
      dbName: k6
      httpMode: GET
      organization: HG
      tlsSkipVerify: true
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
